language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
  - php: nightly

env:
  - SYMFONY_VERSION=""    COMPOSER_OPTS=""
  - SYMFONY_VERSION="2.7" COMPOSER_OPTS="--prefer-lowest"
  - SYMFONY_VERSION="3.0" COMPOSER_OPTS="--prefer-lowest"
  - SYMFONY_VERSION="4.0" COMPOSER_OPTS="--prefer-lowest"

install:
  - composer self-update --snapshot
  - tests/travis/symfony.php
  - composer update $COMPOSER_OPTS

script:
  - vendor/bin/phpunit
  - tests/lint.sh
  - vendor/bin/composer-require-checker

jobs:
  include:
    - stage: coverage
      script:
        - vendor/bin/phpunit --coverage-clover=clover.xml
        - vendor/bin/php-coveralls

git:
  depth: 5

dist: trusty
sudo: false
